if __name__ == '__main__':
	import sys
	f = file("pythonpathes.bat", "wt")
	print >> f, "REM THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT"
	print >> f, "SET PYTHON_HOME=%s" % sys.prefix
	f.close()
else:
	raise ImportError, "This is script"
