from win32com.shell import shell

CODE = """\
CSIDL_DESKTOP = 0x0
CSIDL_INTERNET = 0x1
CSIDL_PROGRAMS = 0x2
CSIDL_CONTROLS = 0x3
CSIDL_PRINTERS = 0x4
CSIDL_PERSONAL = 0x5
CSIDL_FAVORITES = 0x6
CSIDL_STARTUP = 0x7
CSIDL_RECENT = 0x8
CSIDL_SENDTO = 0x9
CSIDL_BITBUCKET = 0xA
CSIDL_STARTMENU = 0xB
CSIDL_MYDOCUMENTS = 0xC
CSIDL_MYMUSIC = 0xD
CSIDL_MYVIDEO = 0xE
CSIDL_DESKTOPDIRECTORY = 0x10
CSIDL_DRIVES = 0x11
CSIDL_NETWORK = 0x12
CSIDL_NETHOOD = 0x13
CSIDL_FONTS = 0x14
CSIDL_TEMPLATES = 0x15
CSIDL_COMMON_STARTMENU = 0x16
CSIDL_COMMON_PROGRAMS = 0x17
CSIDL_COMMON_STARTUP = 0x18
CSIDL_COMMON_DESKTOPDIRECTORY = 0x19
CSIDL_APPDATA = 0x1A
CSIDL_PRINTHOOD = 0x1B
CSIDL_LOCAL_APPDATA = 0x1C
CSIDL_ALTSTARTUP = 0x1D
CSIDL_COMMON_ALTSTARTUP = 0x1E
CSIDL_COMMON_FAVORITES = 0x1F
CSIDL_INTERNET_CACHE = 0x20
CSIDL_COOKIES = 0x21
CSIDL_HISTORY = 0x22
CSIDL_COMMON_APPDATA = 0x23
CSIDL_WINDOWS = 0x24
CSIDL_SYSTEM = 0x25
CSIDL_PROGRAM_FILES = 0x26
CSIDL_MYPICTURES = 0x27
CSIDL_PROFILE = 0x28
CSIDL_SYSTEMX86 = 0x29
CSIDL_PROGRAM_FILESX86 = 0x2A
CSIDL_PROGRAM_FILES_COMMON = 0x2B
CSIDL_PROGRAM_FILES_COMMONX86 = 0x2C
CSIDL_COMMON_TEMPLATES = 0x2D
CSIDL_COMMON_DOCUMENTS = 0x2E
CSIDL_COMMON_ADMINTOOLS = 0x2F
CSIDL_ADMINTOOLS = 0x30
CSIDL_CONNECTIONS = 0x31
CSIDL_COMMON_MUSIC = 0x35
CSIDL_COMMON_PICTURES = 0x36
CSIDL_COMMON_VIDEO = 0x37
CSIDL_RESOURCES = 0x38
CSIDL_RESOURCES_LOCALIZED = 0x39
CSIDL_COMMON_OEM_LINKS = 0x3A
CSIDL_CDBURN_AREA = 0x3B
CSIDL_COMPUTERSNEARME = 0x3D
"""

CSIDL = {}

for key, n in (map(str.strip, line.split('=')) for line in CODE.split('\n') if line):
	CSIDL[key[6:]] = int(n, 16)
	
def getSpecialFolderPath(key):
	"""
	key is one of CSIDL.keys(): "PERSONAL", "APPDATA", etc.
	"""
	return shell.SHGetSpecialFolderPath(0, CSIDL[str(key).upper()], 0)

if __name__ == '__main__':
	print "Available shell folders:"
	keys = CSIDL.keys()
	keys.sort()
	errors = []
	for key in keys:
		try:
			print "%-24s: %s" % (key, getSpecialFolderPath(key))
		except Exception, e:
			errors.append((key, e))
			pass

	if errors:
		print 
		for key, e in errors:
			print "%-24s: ERROR %s: %s" % (key, e.__class__.__name__, e)
		